/*

 BLIPBG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : E:\Coding\Gameboy\Background\bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 38
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define blipBgWidth 32
#define blipBgHeight 18
#define blipBgBank 0

extern unsigned char blipBg[];

/* End of BLIPBG.H */
